if(CHIEFRAY_ENABLE_CUDA)
    include(CheckLanguage)
    check_language(CUDA)
    if(CMAKE_CUDA_COMPILER)
        enable_language(CUDA)
        set(CMAKE_CUDA_STANDARD 17)
        set(CMAKE_CUDA_STANDARD_REQUIRED ON)
        if(NOT DEFINED CMAKE_CUDA_ARCHITECTURES)
            set(CMAKE_CUDA_ARCHITECTURES native)
        endif()
        set(CMAKE_CUDA_SEPARABLE_COMPILATION ON)
        message(STATUS "CUDA enabled (arch=${CMAKE_CUDA_ARCHITECTURES})")
    else()
        message(WARNING
            "CHIEFRAY_ENABLE_CUDA=ON but no CUDA compiler was found; disabling CUDA backend.")
        set(CHIEFRAY_ENABLE_CUDA OFF CACHE BOOL "Enable CUDA" FORCE)
    endif()
endif()